# Generated by Django 3.2.12 on 2022-03-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bairro',
            old_name='Cidade',
            new_name='cidade',
        ),
    ]
